source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Soft Delete with Paranoia
# gem "paranoia"
gem "paranoia", github: "rubysherpas/paranoia", branch: "rails5"

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
# gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'sprockets', '3.6.3'

# Add bootstrap and jquery
gem 'jquery-rails'
gem 'twitter-bootstrap-rails'
gem 'less-rails'

# Install this gem to use Less
gem 'therubyracer'
gem 'therubyrhino'

# Authentication
gem 'devise_token_auth'
gem 'omniauth-google-oauth2'

# HTTP access control
gem 'rack-cors', require: 'rack/cors'

# HTML Pagination
gem 'kaminari'

# Adds authorization functions
gem "pundit"

gem 'config'

# ActiveModel extension that automatically strips all attributes
gem "strip_attributes"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'dotenv-rails'
  gem 'web-console'

  gem 'rspec-rails'
  gem 'json_expressions'
  gem 'simplecov', require: false
  gem 'simplecov-rcov', require: false
  gem 'autodoc'
  gem 'rspec-request_describer'
  gem 'database_cleaner'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'rails_layout'

  gem 'sqlite3'
  gem 'rails-controller-testing'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'rubocop', require: false
  gem 'awesome_print'
  gem 'spring-commands-rspec'
  gem 'rubocop-checkstyle_formatter'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
